version: '2'
services:
  rcgech:
    build:
      context: ./horodateur_api
    environment:
      - WS_URI=https://rinkeby.infura.io/v3/3915211d82c546beaf5336b3c9b9b99a
      - PRIVATE_KEY=87ED42E2AFCF878D1DAA2183AA23F32023F31D377D431BD005207A24B2ACD93A
      - DB_DSN=host=postgres user=tsUhfmkMfY dbname=rcgehorodatage sslmode=disable password=lrwOuiz4gH
      - LOCKED_ADDR=0x88AB30749e745A66262275e0489373D3E0781E74
      - ERROR_THRESHOLD=0.1
      - WARNING_THRESHOLD=1
      - http_proxy=http://squid.forward:3128
      - https_proxy=http://squid.forward:3128
    links:
      - postgres
    depends_on:
      - squid.forward
      - postgres

  webapp:
    build:
      context: ./horodateur_webapp
    environment:
      - KEY_NAME=myservice # The .cert and .key must have the same name
      - IDP_METADATA=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com/ssorec.geneveid.ch_dgsi_blockchain.xml #Public URL where IdP can be found
      - SP_URL=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com:8001 # URL of the service provider
      - API_HOST=rcgech:8090 # API host, is equal to the <api container name>:<port>
      - MAIN_URI=ctihorodateur
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=foo@example.com
      - CSRF_TIME_LIMIT=360
    working_dir: /app
    command: /app/webapp
    volumes:
      - "./myservice.cert:/app/myservice.cert"
      - "./myservice.key:/app/myservice.key"

  postgres:
    image: postgres:9.5
    user: postgres
    environment:
      - POSTGRES_USER=tsUhfmkMfY
      - POSTGRES_PASSWORD=lrwOuiz4gH
      - POSTGRES_DB=rcgehorodatage

  squid.forward:
    image: wernight/squid
    container_name: squid.forward
    restart: always

  # SSL Let's Encrypt config

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/example.com:/etc/nginx/certs:ro # Edit path to right domain name
      - /usr/share/nginx/html
      - /etc/nginx/vhost.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /etc/letsencrypt/live/example.com:/etc/nginx/certs:rw # Edit path to right domain name
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "FILES_PERMS=600"
    volumes_from:
      - nginx-proxy

# Add these env vars to services that need to be reached from the Internet
# VIRTUAL_HOST=example.com ; LETSENCRYPT_HOST=example.com ; LETSENCRYPT_EMAIL= foo@example.com